services:
  - type: web
    name: health-stats-api
    env: node
    root: server/api
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8000

  - type: web
    name: health-stats-tracker-frontend
    env: node
    root: frontend-app
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://health-stats-api.onrender.com
      - key: VITE_API_TIMEOUT
        value: 30000
      - key: VITE_ENABLE_MOCK_DATA
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
