services:
  - type: web
    name: health-stats-api
    env: node
    buildCommand: cd server/api && npm install
    startCommand: cd server/api && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8000

  - type: static
    name: health-stats-frontend
    buildCommand: cd frontend-app && npm install && npm run build
    publishPath: frontend-app/dist
    envVars:
      - key: VITE_API_URL
        value: https://health-stats-api.onrender.com
      - key: VITE_API_TIMEOUT
        value: "30000"
      - key: VITE_ENABLE_MOCK_DATA
        value: "false"
