services:
  - type: web
    name: health-stats-api
    env: node
    buildCommand: cd server/api && npm install
    startCommand: cd server/api && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8000

  - type: web
    name: health-stats-tracker-frontend
    env: node
    buildCommand: cd frontend-app && npm ci && npm run build
    startCommand: cd frontend-app && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://health-stats-api.onrender.com
      - key: VITE_API_TIMEOUT
        value: 30000
      - key: VITE_ENABLE_MOCK_DATA
        value: false
